account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from account import views
app_name='account'
urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

my_app/urls.py
from django.urls import path
from my_app import views
app_name='my_app'
urlpatterns = [
    path('', views.home, name="home"),
    path('create_category/', views.create_category, name='create_category'),
    path('del-category/<int:pk>/', views.CategoryDeleteView.as_view(template_name = "category_delete.html"), name='delete_category'),
    path('update-category/<int:pk>/', views.update_category, name='update_category'),
    path('blogs/<int:pk>', views.view_blog, name='blog_list'),
    path('create_blog/<int:pk>/', views.create_blog, name='create_blog'),
    path('del-blog/<int:pk>/', views.BlogDeleteView.as_view(template_name = "blog_delete.html"), name='delete_blog'),
    path('update-blog/<int:pk>/', views.update_blog, name='update_blog'),
    path('detail_blog/<int:id>/', views.blog_detail, name='detail_blog'),
]

project_3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('my_app.urls', namespace='my_app')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

my_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class CategoryModel(models.Model):
    user = models.ForeignKey(User, related_name='Auth', on_delete=models.CASCADE)
    name = models.CharField("Name", max_length=50)
    title = models.CharField("Title", max_length=50)
    file = models.FileField("File", upload_to='c_files/')



class BlogModel(models.Model):
    category = models.ForeignKey(CategoryModel, related_name='Category', on_delete=models.CASCADE)
    title = models.CharField("Title", max_length=50)
    description = models.TextField(default=None)
    file = models.FileField("File", upload_to='b_files/')

    def __str__(self):
        return self.title
    
    
    

account/forms.py
from django import forms
from django.urls import reverse, reverse_lazy
from django.core.exceptions import ValidationError 

    

my_app/forms.py
from django import forms 
from my_app.models import BlogModel

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogModel
        fields = ['title','description','file']

account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

def login_view(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            messages.success(request, 'Hello ')

            return redirect('my_app:home')
    context = {}
    return render(request, 'login.html', context)
def register_view(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password1')
        re_password = request.POST.get('password2')
        if len(password) > 0 and password == re_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists.')
            else:
                User.objects.create_user(first_name=first_name, last_name=last_name, username=username, password=password)
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Hello ')
                    return redirect('my_app:home')
        else:
            messages.error(request, 'Parol den dal.')
            return redirect('account:register')
    return render(request, 'register.html',{})

my_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from my_app.models import CategoryModel, BlogModel

# Create your views here.
def home(request):
    categories = CategoryModel.objects.all()
    context = {
        'categories':categories,
    }
    return render(request, 'home.html',context)

@login_required(login_url='/account/login/')
def create_category(request):
    user = request.user
    if request.method == 'POST':
        name = request.POST.get('name')
        title = request.POST.get('title')
        file = request.FILES.get('file')
        CategoryModel.objects.create(user=user, name=name, title=title, file=file).save()
        print(user)
        return redirect('my_app:home')
    return render(request, 'create_category.html',{})

def del_category(request, pk):
    CategoryModel.objects.get(id=pk).delete()
    messages.success(request, 'ustunlikli pozuldy ')
    return redirect('my_app:home')

@login_required(login_url='/account/login/')
def update_category(request, pk):
    model = CategoryModel.objects.get(id=pk)
    if request.method == 'POST':
        name = request.POST.get('name')
        title = request.POST.get('title')
        file = request.FILES.get('file')
        model = CategoryModel.objects.get(id=pk)
        model.name = name
        model.title = title
        model.file = file
        model.save()
        return redirect('my_app:home')
    return render(request, 'update_category.html',{'model':model})
def view_blog(request, pk):
    blogs = BlogModel.objects.filter(category_id=pk)
    return render(request, 'blog_list.html',{'blogs':blogs,'pk':pk})

@login_required(login_url='/account/login/')
def create_blog(request, pk):
    user = request.user
    if request.method == 'POST':
        category = CategoryModel.objects.get(id=pk)
        ct=category.name
        title = request.POST.get('title')
        description = request.POST.get('description')
        file = request.FILES.get('file')
        BlogModel.objects.create(category_id=pk, title=title, description=description, file=file).save()
        print(user)
        return redirect('my_app:blog_list',pk)
    return render(request, 'create_blog.html',{"pk":pk})
def del_blog(request, pk):
    model = BlogModel.objects.get(id=pk)
    model.delete()
    messages.success(request, 'ustunlikli pozuldy ')
    return redirect('my_app:blog_list', model.category_id)

@login_required(login_url='/account/login/')
def update_blog(request, pk):
    model = BlogModel.objects.get(id=pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        file = request.FILES.get('file')
        model = BlogModel.objects.get(id=pk)
        model.title = title
        model.description = description
        model.file = file
        model.save()
        return redirect('my_app:blog_list', model.category_id)
    return render(request, 'update_blog.html',{'model':model})
def blog_detail(request, id):
    blog = BlogModel.objects.get(id=id)
    return render(request, 'blog_detail.html',{'blog':blog})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="js sizes customelements history pointerevents postmessage webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers" lang="zxx">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>CRUD</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href=" {% static 'css/home/bootstrap.min.css' %} ">
        <link rel="stylesheet" href="{% static 'css/home/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/ticker-style.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/slicknav.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/fontawesome-all.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/slick.css' %}">
        <link rel="stylesheet" href="{% static 'css/home/nice-select.css' %}">
    </head>
    <body style="overflow: visible;">
        <header>
            <div class="header-area">
                <div class="main-header ">
                    <div class="header-bottom header-sticky">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-xl-6 col-lg-6 col-md-8 header-flex">
                                    <div class="main-menu d-none d-md-block">
                                        <nav>
                                            <ul id="navigation">    
                                                <li>
                                                    <a href="/">Baş sahypa</a>
                                                </li>
                                                <li>
                                                    <a href="{% block category %} {% endblock category %}">{% block text %}{% endblock text %}</a>
                                                </li>
                                                
                                                  
                                                
                                              
                                                {% if messages %}
                                                <li>
                                                    {% for message in messages %}
                                                    {{ message }}
                                                    {% endfor %}
                                                </li>
                                                {% endif %}
                                                {% if user.is_authenticated %}
                                                {{ user }}                                                
                                                {% endif %}
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-6">
                                    <form action="{% url 'my_app:home' %}" method="POST">{% csrf_token %}
                                        <input type="text" name="q" placeholder="Blog gozle" id="">
                                     </form>
                                </div>
                                <div class="col-xl-2 col-lg-2 col-md-4">
                                    <div class="header-right-btn f-right d-none d-lg-block">
                                        {% if user.is_authenticated %}
                                        <a class="btn-link" href="{% url 'account:logout' %}">Hasapdan çykmak</a>
                                        {% else %}
                                        <a class="btn-link" href="{% url 'account:login' %}">Giriş</a>|
                                        <a class="btn-link" href="{% url 'account:register' %}">Registrasiýa</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <br>
        {% block content %}
          
        {% endblock content %}
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </body>
    </html>

templates/blog_delete.html
{% extends "base.html" %}
{% block content %}
<main>
    <div class="trending-area fix">
        <div class="container">
            <div class="trending-main">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="trand-right-single d-flex">
                            <div class="trand-right-img">
                                <a href="{% url 'my_app:detail_blog' object.id %}">
                                {% if object.file.name|slice:"-1:" == 'g' %}
                                <img style="width: 240px; height: 160px;"  src="{{ object.file.url }}" alt="">
                                {% endif %}
                                {% if object.file.name|slice:"-3:" == 'mp4' %}
                                <video style="width: 240px; height: 160px;" src="{{ object.file.url }}"></video>
                                {% endif %}
                            </a>
                            </div>
                            <div class="trand-right-cap">
                                <span class="color1">{{ object.category.title }}</span>
                                <h4><a href="{% url 'my_app:detail_blog' object.id %}">{{ object.title }}</a></h4>
                            </div>
                        </div>
                    </div>
                </div>
                <form method="POST">{% csrf_token %}
                    <button class="btn-danger" type="submit">Hawa</button>
                    <a href="{% url 'my_app:blog_list' object.category_id %}" class="ti-link" style="color: green;">Yok</a>

                </form>
            </div>
            
        </div>
        
    </div>
</main>

  
{% endblock content %}

templates/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% block category %}{% url 'my_app:create_blog' pk %}{% endblock category %}
{% block text %}Blog doredin{% endblock text %}
{% block content %}
<style>
    .pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
}

.pagination a.active {
  background-color: dodgerblue;
  color: white;
}

.pagination a:hover:not(.active) {background-color: #ddd;}
</style>
<main>
    <div class="trending-area fix">
        <div class="container">
            <div class="trending-main">
                <div class="row">
                    <div class="col-lg-4">
                        {% if blogs %}
                        {% for blog in blogs %}
                        <div class="trand-right-single d-flex">
                            <div class="trand-right-img">
                                <a href="{% url 'my_app:detail_blog' blog.id %}">
                                {% if blog.file.name|slice:"-1:" == 'g' %}
                                <img style="width: 240px; height: 160px;"  src="{{ blog.file.url }}" alt="">
                                {% endif %}
                                {% if blog.file.name|slice:"-3:" == 'mp4' %}
                                <video style="width: 240px; height: 160px;" src="{{ blog.file.url }}"></video>
                                {% endif %}
                            </a>
                            </div>
                            <div class="trand-right-cap">
                                <span class="color1">{{ blog.category.title }}</span>
                                <h4><a href="{% url 'my_app:detail_blog' blog.id %}">{{ blog.title }}</a></h4>
                                {% if user.is_authenticated and user == blog.category.user%}
                                <a style="color: red;" href="{% url 'my_app:delete_blog' blog.id %}">
                                    <small>Poz</small>
                                </a> | 
                                <a style="color:green" href="{% url 'my_app:update_blog' blog.id %}">
                                    <small>Uytget</small>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="trand-right-single d-flex">
                            <div class="trand-right-img">
                                <a href="{% url 'my_app:create_blog' pk %}">
                                    <img style="width: 120px; height: 100px;" src="{% static 'download.jpeg' %}" alt="">
                                </a>
                            </div>
                            <div class="trand-right-cap">
                                <span class="color1">Täze blog dörediň</span>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
                
                {% if count_pag and blogs.paginator.num_pages >= 2  %}
                <div> 
                    <div class="pagination">
                        {% if blogs.has_previous %}
                        <a href="?page={{ blogs.previous_page_number }}">&laquo;</a>  
                        {% endif %}
                        {% for page in count_pag %}
                        <a class="{% if blogs.number == page %}active{% endif %}" href="?page={{ page }}">{{ page }}</a>                     
                        {% endfor %}
                        {% if blogs.has_next %}
                        <a href="?page={{ blogs.next_page_number }}">&raquo;</a>  
                        {% endif %}
                      </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/create_blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <div class="trending-area fix">
        <div class="container">
            <div class="trending-main">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="trending-bottom">
                            <div class="row" style="text-align: center;">
                                <div class="col-lg-12">
                                    <form enctype="multipart/form-data" action="{% url 'my_app:create_blog' pk %}" method="POST">{% csrf_token %}
                                        <label>Title</label><br>
                                        <input type="text" name="title"><br><br>
                                        <label>Description</label><br>
                                        <textarea name="description" cols="30" rows="10"></textarea><br><br>
                                        <label>File</label><br>
                                        <input type="file" name="file"><br><br>
                                        <button type="submit" class="btn-success">Create</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/create_category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <div class="trending-area fix">
        <div class="container">
            <div class="trending-main">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="trending-bottom">
                            <div class="row" style="text-align: center;">
                                <div class="col-lg-12">
                                    <form enctype="multipart/form-data" action="{% url 'my_app:create_category' %}" method="POST">{% csrf_token %}
                                        <label>Name</label><br>
                                        <input type="text" name="name"><br><br>
                                        <label>Title</label><br>
                                        <input type="text" name="title"><br><br>
                                        <label>File</label><br>
                                        <input type="file" name="file"><br><br>
                                        <button type="submit" class="btn-success">Create</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block category %}{% url 'my_app:create_category' %}{% endblock category %}
{% block text %}Kategoriya doredin{% endblock text %}
{% block content %}
{% if q %}
<h5 style="text-align: center;">Tapylan Bloglar</h5>
{% endif %}
<hr>
<main>
    <div class="trending-area fix">
        <div class="container">
          
            <div class="trending-bottom">
                <div class="row">
                    {% if q %}
                    {% for categori in q %}
                    <div class="col-lg-4">
                        <div class="single-bottom mb-35">
                            <div class="trend-bottom-img mb-30">
                                <a href="{% url 'my_app:detail_blog' categori.id %}">
                                    {% if categori.file.name|slice:"-1:" == 'g' %}
                                    <img style="width: 240px; height: 160px;"  src="{{ categori.file.url }}" alt="">
                                    {% endif %}
                                    {% if categori.file.name|slice:"-3:" == 'mp4' %}
                                    <video style="width: 240px; height: 160px;" src="{{ categori.file.url }}"></video>
                                    {% endif %}
                                </a>
                            </div>
                            {% if user.is_authenticated and user == categori.user%}
                            <a style="color: red;" href="{% url 'my_app:delete_category' categori.id %}"><small>Poz</small></a> | 
                            <a style="color:green" href="{% url 'my_app:update_category' categori.id %}"><small>Uytget</small></a>
                            {% endif %}
                            <div class="trend-bottom-cap">
                                <span class="color1">{{ categori.category.name }}</span>
                                <h4>
                                    <a href="{% url 'my_app:detail_blog' categori.id %}">
                                        {{ categori.title }}
                                    </a>
                                </h4>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                   
<!-- else -->
                    {% else %}
                    {% for categori in categories %}
                    <div class="col-lg-4">
                        <div class="single-bottom mb-35">
                            <div class="trend-bottom-img mb-30">
                                {% if categori.file.name|slice:"-1:" == 'g' %}
                                <a href="{% url 'my_app:blog_list' categori.id %}">
                                    <img style="width: 240px; height: 160px;"  src="{{ categori.file.url }}" alt="">
                                </a>    
                                {% endif %}
                            </div>
                            {% if user.is_authenticated and user == categori.user%}
                            <a style="color: red;" href="{% url 'my_app:delete_category' categori.id %}"><small>Poz</small></a> | 
                            <a style="color:green" href="{% url 'my_app:update_category' categori.id %}"><small>Uytget</small></a>
                            {% endif %}
                            <div class="trend-bottom-cap">
                                <span class="color1">{{ categori.name }}</span>
                                <h4>
                                    <a href="{% url 'my_app:blog_list' categori.id %}">
                                        {{ categori.title }}
                                    </a>
                                </h4>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                    
                    
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html style="overflow: hidden;">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Register page</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="keywords" content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design">
		<script type="application/x-javascript"> 
			addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); 
			function hideURLbar(){ window.scrollTo(0,1); } 
		</script>
		<style>
		.errorlist {
			list-style-type:none;
			}
		</style>
 <!-- Bootstrap Core CSS -->
<link href=" {% static 'bootstrap.min.css' %} " rel="stylesheet" type="text/css">
<!-- Custom CSS -->
<link href=" {% static 'style.css' %} " rel="stylesheet" type="text/css">
<!-- Graph CSS -->
<link href=" {% static 'font-awesome.css' %} " rel="stylesheet"> 
<!-- jQuery -->
<link href="file://fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400" rel="stylesheet" type="text/css">
<!-- lined-icons -->
<link rel="stylesheet" href=" {% static 'icon-font.min.css' %} " type="text/css">
<!-- //lined-icons -->
<script src=" {% static 'jquery-1.10.2.min.js' %} "></script>
<!--clock init--> 
</head> 
<body>
	<div class="error_page">
		<div class="error-top up">
			<h2 class="inner-tittle page">Sign Up</h2>
			<div class="login">
				<form action='{% url "account:login" %}' method='post'>{% csrf_token %}
					<input class="text" type="text" placeholder="username" name="username" required>
					<input class="text" type="password" placeholder="password" name="password" required>
					<div class="submit"><input type="submit" onclick="myFunction()" value="Sign up"></div>
					<div class="new">
						<p class="sign up">Don't have an account yet? <a href="{% url 'account:register' %}"> Register here.</a></p>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="footer sign">
		<div class="error-btn">
			<a class="read fourth" href="/">Return to Home</a>
		</div>
	</div>
<!--js -->
	<script src=" {% static 'jquery.nicescroll.js' %} "></script>
	<script src=" {% static 'scripts.js' %} "></script><div id="ascrail2000" class="nicescroll-rails" style="width: 5px; z-index: 1000; background: rgb(0, 37, 97); cursor: default; position: fixed; top: 0px; height: 100%; right: 0px; opacity: 0;"><div style="position: relative; top: 1px; float: right; width: 5px; height: 498px; background-color: rgb(0, 198, 215); border: 0px; background-clip: padding-box; border-radius: 10px;"></div></div><div id="ascrail2000-hr" class="nicescroll-rails" style="height: 5px; z-index: 1000; background: rgb(0, 37, 97); position: fixed; left: 0px; width: 100%; bottom: 0px; cursor: default; opacity: 0; display: none;"><div style="position: relative; top: 0px; height: 5px; width: 1312px; background-color: rgb(0, 198, 215); border: 0px; background-clip: padding-box; border-radius: 10px;"></div></div>
<!-- Bootstrap Core JavaScript -->
	<script src=" {% static 'bootstrap.min.js' %} "></script>

</body></html>

templates/update_blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <div class="trending-area fix">
        <div class="container">
            <div class="trending-main">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="trending-bottom">
                            <div class="row" style="text-align: center;">
                                <div class="col-lg-12">
                                    <form enctype="multipart/form-data" action="{% url 'my_app:update_blog' model.id %} " method="POST">
                                        {% csrf_token %}
                                        <label>Name</label><br>
                                        <input type="text" value="{{ model.title }}" name="title"><br><br>
                                        <label>Title</label><br>
                                        <textarea name="description" cols="30" rows="10">{{ model.description }}</textarea><br><br>
                                        <label>File</label><br>
                                        <input type="file" name="file" required><br><br>
                                        <button type="submit" class="btn-success">Update</button>
                                        <br><br>
                                        <h6 style="color: red;"><a href="/">Yza</a></a></h6>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}